-- CE Sandton demo data. Stratum's own seed.sql (kept here as merge=ours)
-- seeds event-series editions the events module (off here) doesn't use.
-- Phase 7 replaces this with real demo data: 2 locations, 6 cells, ~300
-- members across all ages/genders/statuses, 12 weeks of services, 2
-- Foundation School cohorts and sample message campaigns.
--
-- Loaded by `supabase db reset` (see config.toml [db.seed]), or paste into
-- the Supabase SQL editor. Safe to re-run (currently a no-op).
