import type { Role } from "@/lib/handbook/types";

// Offices from Part A of the SOP (amended 2015), wording kept as written.
const TITHE_HQ =
  "Pays tithe to the HQ, BLW Inc through the designated account, with proof of payment submitted to the designated officer in the office of the President, BLW Inc";

const ZONAL_SECRETARY_FACTS = [
  { label: "Appointed by", value: "The Zonal Director, approved by the Regional/Zonal Pastor in conjunction with the IEC of The Haven" },
  { label: "Eligibility", value: "Must have previously functioned at a minimum level of a Haven Deputy Governor" },
  { label: "Reports to", value: "The Zonal Director, in all matters" },
  { label: "Tenure", value: "Two years, or as determined by the Zonal Director subject to approval of the Regional Pastor and the IEC" },
];

export const roles: Role[] = [
  {
    id: "cec",
    title: "Central Executive Council, BLW",
    level: "Ministry",
    parentId: null,
    summary: "Determines, supervises and approves the activities of The Haven.",
    responsibilities: [
      "The CEC, BLW shall determine, supervise, and approve the activities of The Haven",
      "The supervisory responsibility shall be vested in The Haven International Executive Committee (IEC) presided over by the International President of The Haven who shall report directly to the President, BLW Nation in all matters of The Haven",
    ],
    facts: [],
  },
  {
    id: "iec",
    title: "International Executive Committee (IEC)",
    level: "International",
    parentId: "cec",
    summary: "The International President and the International Directors — sets The Haven's goals, targets and thresholds.",
    responsibilities: [
      "The IEC shall set the goals and targets for The Haven based on the central ministry direction given by the President of BLW Inc.",
      "The IEC shall determine the global financial participation by The Haven Nation within a given period based on the central/global ministry direction given by the President of BLW Inc.",
      "The IEC shall determine the minimum financial participation threshold for all Haven Zones within a given period",
      "The IEC shall be responsible for the coordination and achievement of the set goals and targets for The Haven Nation for a given period",
      "The IEC shall be responsible for developing and executing The Haven growth strategy through different training programmes, meetings, conventions, and financial targets",
      "The IEC shall be responsible for the discipline and tenure of Zonal Directors",
    ],
    facts: [
      { label: "Members", value: "The International President of The Haven and the International Directors" },
      { label: "Headed by", value: "The International President of The Haven" },
    ],
  },
  {
    id: "international-president",
    title: "The Haven International President",
    level: "International",
    parentId: "iec",
    summary: "Leads and coordinates The Haven at the Ministry level and provides its spiritual leadership.",
    responsibilities: [
      "The Haven shall be led and coordinated at the Ministry level by a President referred to as The Haven International President",
      "Shall be responsible for providing Spiritual leadership and direction for The Haven Ministry",
      "With other members of the IEC, shall be responsible for developing, executing and reviewing of strategies, policies, and practices to achieve set objectives set by the ministry for The Haven Nation",
      "With other members of the IEC, shall be responsible for determining the annual calendar of The Haven and submit same to the President, BLW Nation for approval",
      "Shall be responsible for coordinating and presenting the annual report of The Haven to the President, BLW Nation for performance evaluation",
      "For focus and effectiveness, shall not coordinate or pastor a church while in office",
    ],
    facts: [
      { label: "Reports to", value: "The President, BLW Nation" },
      { label: "Tenure", value: "Determined by the President, BLW Nation" },
      { label: "Tithe", value: TITHE_HQ },
    ],
  },
  {
    id: "director-operations",
    title: "International Director, Operations",
    level: "International",
    parentId: "international-president",
    summary: "Supervises execution of The Haven strategy, expansion, projects and zonal performance globally.",
    responsibilities: [
      "Shall be responsible for the overall supervision of the execution of The Haven strategy and policies globally",
      "Shall be responsible for coordinating the expansion of The Haven work globally",
      "Shall be responsible for coordinating and execution of international programmes and meetings in The Haven",
      "Shall be responsible for the execution of Haven projects globally",
      "Shall be responsible for monitoring and coordination of global performances by zones in The Haven",
      "Shall be responsible for the overall supervision of The Haven zonal activities",
      "Shall be responsible for coordination of participation of Haven leaders and members at the IPPC annually and this shall include the execution of The Haven Exhibition strategy",
    ],
    facts: [
      { label: "Reports to", value: "The International President of The Haven" },
      { label: "Appointment & tenure", value: "Determined by the CEC, BLW Inc" },
      { label: "Tithe", value: TITHE_HQ },
    ],
  },
  {
    id: "director-administration",
    title: "International Director, Administration",
    level: "International",
    parentId: "international-president",
    summary: "Runs the International Secretariat, training, the membership database and leadership liaison.",
    responsibilities: [
      "Shall be responsible for running of The Haven International Secretariat machinery for effective mobilization of The Haven Ministry",
      "Shall be responsible for the development and management of infrastructures to support The Haven work globally",
      "Shall be responsible for The Haven training facilitation and administration",
      "Shall be responsible for developing and maintaining of The Haven Ministry membership database",
      "Shall be responsible for leadership liaison in The Haven globally",
      "Shall be responsible for Church Pastors liaison globally",
      "Shall be responsible for organizing the national leadership meetings, annual Haven Conventions, and supervision of the Zonal Conventions of The Haven",
    ],
    facts: [
      { label: "Reports to", value: "The Haven International President" },
      { label: "Appointment & tenure", value: "Determined by the CEC, BLW" },
      { label: "Tithe", value: TITHE_HQ },
    ],
  },
  {
    id: "director-finance",
    title: "International Director, Finance",
    level: "International",
    parentId: "international-president",
    summary: "Owns The Haven's financial strategy, bank accounts and global financial reporting.",
    responsibilities: [
      "Shall be responsible for coordinating the development and execution of financial strategies of The Haven globally",
      "Shall be responsible for coordinating and directing the financial processes and procedures of The Haven globally",
      "Shall be responsible for the coordination of payment of monthly membership dues, project seeds and other financial targets of The Haven",
      "Shall be responsible for running and maintaining all bank accounts of The Haven",
      "Shall be responsible for the compilation and rendition of the global financial monthly, quarterly and annual reports for The Haven",
      "Shall be responsible for creating investment portfolios, execution of funds management strategies to effectively manage The Haven finances",
      "Shall be responsible for the coordination of all financial reports and consolidation into a global Haven ministry financial report for submission to The Haven International President",
      "Shall be responsible for coordination of international financial regulations and compliance in conjunction with the Zonal Directors at international locations",
      "Shall be responsible for membership financial intelligence services",
    ],
    facts: [
      { label: "Reports to", value: "The Haven International President" },
      { label: "Appointment & tenure", value: "Determined by the CEC, BLW" },
      { label: "Tithe", value: TITHE_HQ },
    ],
  },
  {
    id: "secretariat-staff",
    title: "International Secretariat Staff",
    level: "International",
    parentId: "international-president",
    summary: "Full-time staff of The Haven International supporting the International Directors.",
    responsibilities: [
      "They shall support the International Directors in the execution of their directorate mandate as itemized under the responsibilities of the International Directors",
      "Recruitment, discipline and promotions shall follow already established BLW Nation staff procedures and standards",
    ],
    facts: [{ label: "Employment", value: "Full time staff of The Haven International" }],
  },
  {
    id: "zonal-director",
    title: "Zonal Director",
    level: "Zone",
    parentId: "international-president",
    summary: "Supervises, coordinates and controls a Zone, and is primarily responsible for its chapters' performance.",
    responsibilities: [
      "A Zonal Director shall be responsible for the supervision, coordination and control of a Zone",
      "A Zonal Director shall be primarily responsible for the performances, growth and success of The Haven Chapters in the Zone",
      "A Zonal Director shall be responsible for setting goals and targets for Zone and chapters in the Zone and ensuring that they are achieved",
      "The annual financial targets set for the Zone must conform to the minimum annual financial participation threshold for the Zone’s category based on Ministry global targets",
      "A Zonal Director shall supervise and coordinate The Haven Governors under the Zone",
      "A Zonal Director shall concur to the appointment of a Chapter Governor by the Church Pastor. Where the Zonal Director disagrees with the candidate appointed as a Chapter Governor, the IEC and the Regional Pastor will be duly notified to resolve the appointment",
      "A Zonal Director shall coordinate report rendition and ensure all Haven directives and policies are executed in the chapters under his/her Zone",
      "The Zone shall operate a Zonal Secretariat which should be based in any church facility under the church ministry region or zone within which the Zone operates",
    ],
    facts: [
      { label: "Reports to", value: "The Haven International President" },
      {
        label: "Criteria",
        value:
          "A Governor/former Governor who has displayed exceptional leadership in positioning their chapter for superior performance — consistent financial contribution to Global Projects, mobilisation of leaders to strategic leadership conferences, and growth with bona fide members",
      },
      {
        label: "Appointed by",
        value: "The Regional Pastor (or by voting at the NEA), ratified by the President, BLW Nation; commissioned/ordained by the CEC",
      },
      { label: "Tenure", value: "Two years; may be returned for another two years via voting, based on performance, at the NEA under the supervision of the IEC" },
      { label: "Discipline", value: "Determined by the IEC of The Haven" },
      { label: "Tithe", value: TITHE_HQ },
    ],
    position: "zonal_director",
  },
  {
    id: "zonal-secretary-operations",
    title: "Zonal Secretary, Operations",
    level: "Zone",
    parentId: "zonal-director",
    summary: "Executes the zone's goals and targets and drives growth with the Chapter Governors.",
    responsibilities: [
      "Shall be responsible for the execution and operation of all Haven goals and targets in the zone",
      "Shall directly work with the Chapter Governors to achieve set goals",
      "Shall be responsible for the execution of all zonal training and developmental programmes",
      "Shall drive growth in the zone on behalf of the Zonal Director",
    ],
    facts: ZONAL_SECRETARY_FACTS,
    position: "zonal_secretary",
    portfolio: "operations",
  },
  {
    id: "zonal-secretary-finance",
    title: "Zonal Secretary, Finance",
    level: "Zone",
    parentId: "zonal-director",
    summary: "Directs the zone's financial processes, bank accounts and financial reports.",
    responsibilities: [
      "Shall be responsible for coordinating and directing the financial processes and procedures of The Haven at the zonal level",
      "Shall be responsible for the coordination of payment of monthly membership dues, project seeds and other financial targets of The Haven",
      "Shall be responsible for running and maintaining all bank accounts of The Haven in the zone",
      "Shall be responsible for the compilation and rendition of the zonal financial monthly, quarterly and annual reports",
    ],
    facts: ZONAL_SECRETARY_FACTS,
    position: "zonal_secretary",
    portfolio: "finance",
  },
  {
    id: "zonal-secretary-administration",
    title: "Zonal Secretary, Administration",
    level: "Zone",
    parentId: "zonal-director",
    summary: "Runs zonal training administration, the zonal membership database and leadership liaison.",
    responsibilities: [
      "Shall be responsible for The Haven training facilitation and administration in the zone",
      "Shall be responsible for developing and maintaining of the zonal membership database",
      "Shall be responsible for leadership liaison in the zone",
    ],
    facts: ZONAL_SECRETARY_FACTS,
    position: "zonal_secretary",
    portfolio: "administration",
  },
  {
    id: "zonal-secretary-programmes",
    title: "Zonal Secretary, Programmes",
    level: "Zone",
    parentId: "zonal-director",
    summary: "Executes zonal programmes, meetings and trainings, and their logistics.",
    responsibilities: [
      "Shall be responsible for the execution of all zonal programmes, meetings, trainings",
      "Shall be responsible for all forms of logistics in the administration of the zone",
      "Shall work in conjunction with Chapter Governors in the effective execution of programmes in The Haven Chapters",
    ],
    facts: ZONAL_SECRETARY_FACTS,
    position: "zonal_secretary",
    portfolio: "programs",
  },
  {
    id: "chapter-governor",
    title: "Chapter Governor",
    level: "Chapter",
    parentId: "zonal-director",
    summary:
      "Executor of The Haven mandate at chapter level. Applies to whoever leads a chapter — Governor, Deputy Governor, Assistant Governor, Coordinator or Ag. Coordinator.",
    responsibilities: [
      "The Haven Governor shall be responsible for the coordination, supervision and control of all Haven activities in a Christ Embassy Church",
      "The Haven Governor shall be responsible for providing leadership and direction at the chapter level of The Haven",
      "He/She shall be responsible for developing, executing and reviewing strategies for achieving all given goals/targets and sharing the vision of The Haven at the chapter level",
      "He/She shall be responsible for growing the membership base and the development of the chapter members in The Haven vision",
      "He/She shall be responsible for coordinating and submitting monthly administrative and financial reports to the local CE church Pastor and The Haven International Secretariat through the Zonal Director",
      "For focus and effectiveness, the Haven Governor shall not coordinate or pastor a church while in office",
    ],
    facts: [
      { label: "Reports to", value: "The Zonal Director, functionally and administratively" },
      { label: "Nominated by", value: "The Pastor of a CE Church with the concurrence of the Haven Zonal Director" },
      { label: "Tenure", value: "One year; a maximum of two terms, and may contest again after the fourth year" },
      { label: "Tithe", value: "Pays tithe to the local church" },
    ],
    position: "governor",
  },
  {
    id: "assistant-governor-administration",
    title: "Assistant Governor, Administration",
    level: "Chapter",
    parentId: "chapter-governor",
    summary: "Plans and executes the chapter's meetings, programmes and projects, the cell system and member welfare.",
    responsibilities: [
      "Shall be responsible for planning and executing all meetings, programs and projects in The Haven chapter",
      "Shall be responsible for supervising the cell system effectively in The Haven Chapter",
      "Shall be responsible for executing membership development strategies in the chapter",
      "Shall supervise the maintenance of the membership database in the chapter",
      "Shall be responsible for supervising members’ welfare in the chapter",
      "Supervises and coordinates the collation of monthly administrative reports in the chapter",
      "Shall coordinate the activities of the General Secretary and Special Duties Secretary in the chapter",
    ],
    facts: [{ label: "Tenure", value: "Determined by the CE church Pastor" }],
  },
  {
    id: "assistant-governor-finance",
    title: "Assistant Governor, Finance",
    level: "Chapter",
    parentId: "chapter-governor",
    summary: "Executes the chapter's financial strategy, dues and seeds, member statements and the monthly financial report.",
    responsibilities: [
      "Shall be responsible for executing all financial strategies in the chapter",
      "Shall be responsible for supervising all financial goals/projects/targets",
      "Shall coordinate payment of the monthly membership dues and project seeds in the chapter",
      "Shall supervise the generation of a monthly statement of account for every Haven member to acknowledge their financial commitment",
      "Shall prepare a monthly financial report for the chapter to be submitted to the Governor and the Zonal Director",
      "Shall be responsible for supervising running of Haven accounts in the chapter",
      "Shall coordinate the activities of the Financial Secretary (s) in the chapter",
    ],
    facts: [{ label: "Tenure", value: "Determined by the CE church Pastor" }],
  },
  {
    id: "general-secretary",
    title: "General Secretary",
    level: "Chapter",
    parentId: "assistant-governor-administration",
    summary: "Runs the chapter's administration: meetings, minutes, the membership database and reports.",
    responsibilities: [
      "The General Secretary shall be responsible for all administrative activities in the chapter",
      "Shall summon meetings, take minutes of meetings and circulate meetings’ reports in the chapter",
      "Shall be responsible for maintaining membership database in the chapter",
      "Shall develop the monthly administrative and financial reports for submission to the Governor",
      "Shall liaise with cell and cell leaders to ensure effective running of the cell system in the chapter",
    ],
    facts: [
      { label: "Reports to", value: "Assistant Governor, Administration" },
      { label: "Tenure", value: "Determined by the CE church Pastor" },
    ],
  },
  {
    id: "special-duties-secretary",
    title: "Special Duties Secretary",
    level: "Chapter",
    parentId: "assistant-governor-administration",
    summary: "Assists with programmes and events, and looks after member welfare.",
    responsibilities: [
      "Shall assist the Assistant Governor Admin in planning and execution of programs, projects and events",
      "Shall be responsible for the maintenance of membership welfare in the chapter. This will include celebrating birthdays, childbirth notification, baby dedication, marriages, thanksgiving, condolence visits (if any)",
    ],
    facts: [],
  },
  {
    id: "financial-secretary",
    title: "Financial Secretary",
    level: "Chapter",
    parentId: "assistant-governor-finance",
    summary: "Collects, receipts and banks all monies in the chapter.",
    responsibilities: [
      "The Financial Secretary shall be responsible for collecting all monies – dues, project seeds, other projects in the chapter",
      "Shall be responsible for banking this monies and maintain a standard accounting procedure for book keeping",
      "Shall be responsible for issuing receipts to members for monies given",
      "Shall assist the Assistant Governor, Finance in preparing the monthly financial report for the chapter",
      "There can be more than one (1) Financial Secretary where there are multiple projects being executed",
    ],
    facts: [{ label: "Reports to", value: "Assistant Governor, Finance" }],
  },
];
